const { runOpenSsl, ALICE_PUBLIC_KEY, ALICE_PRIVATE_KEY, MALLORY_PRIVATE_KEY } = require('./opensslService');
const os = require('os');
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');

/**
 * Parses the hex hash from OpenSSL's 'dgst' command output.
 * Output format: SHA2-256(file.txt)= <hex>
 */
function parseHashFromOpenSslOutput(output) {
    return output.split('=').pop().trim();
}

function executeAttack(attackType) {
  let messageFile, signatureFile;
  let result = {};

  try {
    const timestamp = Date.now();
    messageFile = path.join(os.tmpdir(), `crp_attack_msg_${timestamp}.txt`);
    signatureFile = path.join(os.tmpdir(), `crp_attack_sig_${timestamp}.bin`); // .bin for binary signature

    let messageContent;
    let signatureHex;
    let openSslResult;

    switch (attackType) {
      case 'random_signature': {
        messageContent = 'Transfer ₹1000 to Bob';
        fs.writeFileSync(messageFile, messageContent, 'utf8');

        // Generate 256 random bytes as a fake signature
        const fakeSignature = crypto.randomBytes(256);
        fs.writeFileSync(signatureFile, fakeSignature);
        signatureHex = fakeSignature.toString('hex');

        try {
          openSslResult = runOpenSsl([
            'dgst', '-sha256', '-verify', ALICE_PUBLIC_KEY, '-signature', signatureFile, messageFile
          ]);
        } catch (e) {
          openSslResult = e.stdout ? e.stdout.trim() : (e.stderr ? e.stderr.trim() : 'Verification Failure');
        }

        result = {
          attack: "Random Signature Attack",
          goal: "Forge a signature without holding any private key to impersonate Alice.",
          result: openSslResult.includes('Verified OK') ? "SUCCESS" : "FAILED",
          reason: openSslResult.includes('Verified OK') ? "Unexpected success (critical flaw)" : "Signature does not correspond to Alice's private key.",
          signatureHex: signatureHex,
          openSslResult: openSslResult
        };
        break;
      }

      case 'wrong_key': {
        messageContent = 'Transfer ₹1000 to Bob';
        fs.writeFileSync(messageFile, messageContent, 'utf8');

        // Sign with Mallory's private key
        const mallorySignOutput = runOpenSsl([
          'dgst', '-sha256', '-sign', MALLORY_PRIVATE_KEY, '-out', signatureFile, messageFile
        ]);
        // Read the generated signature to get its hex representation
        signatureHex = fs.readFileSync(signatureFile).toString('hex');

        // Verify with Alice's public key
        try {
          openSslResult = runOpenSsl([
            'dgst', '-sha256', '-verify', ALICE_PUBLIC_KEY, '-signature', signatureFile, messageFile
          ]);
        } catch (e) {
          openSslResult = e.stdout ? e.stdout.trim() : (e.stderr ? e.stderr.trim() : 'Verification Failure');
        }

        result = {
          attack: "Wrong Key Attack",
          goal: "Impersonate Alice using Mallory's valid RSA keypair.",
          result: openSslResult.includes('Verified OK') ? "SUCCESS" : "FAILED",
          reason: openSslResult.includes('Verified OK') ? "Unexpected success (critical flaw)" : "Signature generated by a different private key.",
          signatureHex: signatureHex,
          openSslResult: openSslResult
        };
        break;
      }

      case 'private_key_compromise': {
        messageContent = 'Transfer ₹500000 to Attacker';
        fs.writeFileSync(messageFile, messageContent, 'utf8');

        // Sign with Alice's stolen private key
        const aliceSignOutput = runOpenSsl([
          'dgst', '-sha256', '-sign', ALICE_PRIVATE_KEY, '-out', signatureFile, messageFile
        ]);
        signatureHex = fs.readFileSync(signatureFile).toString('hex');

        // Verify with Alice's public key
        try {
          openSslResult = runOpenSsl([
            'dgst', '-sha256', '-verify', ALICE_PUBLIC_KEY, '-signature', signatureFile, messageFile
          ]);
        } catch (e) {
          openSslResult = e.stdout ? e.stdout.trim() : (e.stderr ? e.stderr.trim() : 'Verification Failure');
        }
        
        result = {
          attack: "Private Key Compromise",
          goal: "Demonstrate catastrophic failure if Alice's private key is stolen.",
          result: openSslResult.includes('Verified OK') ? "SUCCESS" : "FAILED",
          reason: openSslResult.includes('Verified OK') ? "Attacker possessed Alice's private key." : "Verification failed unexpectedly.",
          signatureHex: signatureHex,
          openSslResult: openSslResult
        };
        break;
      }

      default:
        throw new Error('Invalid attack type');
    }
  } finally {
    if (messageFile && fs.existsSync(messageFile)) fs.unlinkSync(messageFile);
    if (signatureFile && fs.existsSync(signatureFile)) fs.unlinkSync(signatureFile);
  }

  return result;
}

module.exports = { executeAttack };
